variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  GITLAB_API_TOKEN: vtWxX9j7b76rQ_ucQryj

image: maven:3.8.5-openjdk-17

stages:
  - document

cache:
  paths:
    - .m2/repository
    - target

document_job:
  stage: document
  script:
    - mvn javadoc:javadoc
    - mv target/site/apidocs/ ./
    - git config user.email "gitlab-ci@example.com"
    - git config user.name "GitLab CI"
    - git add apidocs
    - git commit -m "Update JavaDoc"
    - git push origin HEAD:main
  only:
    - main
