variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  GITLAB_API_TOKEN: vtWxX9j7b76rQ_ucQryj

image: maven:3.8.5-openjdk-17

stages:
  - build
  - test
  - package
  - release

cache:
  paths:
    - .m2/repository
    - target

build_job:
  stage: build
  tags:
    - docker

  script:
    - echo "Maven compile started"
    - "mvn compile -B"

test_job:
  stage: test
  tags:
    - docker

  script:
    - echo "maven test started"
    - "mvn clean test -B"

package_job:
  stage: package
  tags:
    - docker

  script:
    - echo "Maven packaging started"
    - "mvn package -B"

release_job:
  stage: release
  tags:
    - erik
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: never                                  # Do not run this job when a tag is created manually
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run this job when commits are pushed or merged to the default branch
  script:
    - echo "running release_job for $TAG"
  release:                                         # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: 'v0.$CI_PIPELINE_IID'                # The version is incremented per pipeline.
    description: 'v0.$CI_PIPELINE_IID'
    ref: '$CI_COMMIT_SHA'                          # The tag is created from the pipeline SHA.
