variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:3-jdk-17

stages:
  - build
  - test
  - package

cache:
  paths:
    - .m2/repository
    - target

build_job:
  stage: build
  tags:
    - docker

  script:
    - echo "Maven compile started"
    - "mvn compile -B"


test_job:
  stage: test
  tags:
    - docker

  script: 
    - echo "maven test started"
    - "mvn clean test -B"


package_job:
  stage: package
  tags:
    - docker

  script:
    - echo "Maven packaging started"
    - "mvn package -B"
